/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c4c6cd",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#18a659",
        "secondary-fixed": "#cfe5ff",
        "on-error": "#ffffff",
        "primary-fixed": "#d2e4fb",
        "on-tertiary-fixed-variant": "#005228",
        "on-primary-fixed": "#0b1d2d",
        "inverse-primary": "#b7c8de",
        "surface-container-high": "#d9eaff",
        "on-background": "#051d30",
        "tertiary-fixed": "#7efba4",
        "primary": "#041627",
        "secondary-fixed-dim": "#b3c9e2",
        "on-error-container": "#93000a",
        "outline": "#74777d",
        "on-primary-container": "#8192a7",
        "inverse-on-surface": "#e8f2ff",
        "surface-container-highest": "#cfe5ff",
        "tertiary-fixed-dim": "#61de8a",
        "on-tertiary": "#ffffff",
        "surface-tint": "#4f6073",
        "secondary-container": "#cce2fc",
        "surface-bright": "#f7f9ff",
        "surface-container": "#e3efff",
        "on-secondary-container": "#50657b",
        "surface-container-low": "#edf4ff",
        "on-surface": "#051d30",
        "on-secondary-fixed": "#051d30",
        "secondary": "#4b6076",
        "primary-container": "#1a2b3c",
        "on-secondary-fixed-variant": "#34495e",
        "background": "#f7f9ff",
        "tertiary-container": "#003115",
        "surface-dim": "#c6dcf6",
        "surface": "#f7f9ff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "#cfe5ff",
        "tertiary": "#001a08",
        "on-surface-variant": "#44474c",
        "inverse-surface": "#1d3246",
        "on-primary-fixed-variant": "#38485a",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b7c8de",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#00210c"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
